// This file is autogenerated, please do not modify directly!

#include "C:/Users/hands/Documents/GitHub/VMangos-core/modules/mod_sample/src/loader.h"


void AddModuleScripts() {
    Addmod_sampleScripts();
}
